### ISSUE TITLE
Vertical scrollbar always showing

### ISSUE THREAD

**Issue by zHaytam** [chromelyapps/demo-projects#15]
Hello,

When running the regular demo, a vertical scrollbar is always showing as if the content (html) is longer than the window's height, even when it's not.  
Also, in the movies list example, there are 2 scrollbars, one from the html and the other from Chromely.

How can I remove it? Knowing that changing the height in the config files doesn't change anything. 

Thank you!

**Comment by mattkol** [comment]
@zHaytam the demos are just guides to show how to use Chromely..with basic configurations and inter-process communication between browser and renderer via the Controllers.

It is not meant for any UI controls work or perfection. The UI controls just help to facilitate those features.

I will suggest you tweak the css files or inline css to get what you want or use any UI/JavaScript framework of your choice.

If you tweak the Demos and you will like to share your improvement with the community we welcome that too.

Thanks.
