### ISSUE TITLE
CrossPlatDemo startup

### ISSUE THREAD

**Issue by merl111** [chromelyapps/demo-projects#18]
I followed the steps in the readme, I can `restore`, `build` and `run` without any problems or errors. Also the initial download of the missing binaries was successful.

What I get after `dotnet run`:

```
2020-03-21 11:27:47.176 [INFO] Running MacOSX chromium 77.0.3865.120
On CefGlue child process launch arguments:
/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/crossplatdemo --type=gpu-process --field-trial-handle=1718379636,5549198414550298470,15611372194352481318,131072 --disable-features=OutOfBlinkCors --no-sandbox --locales-dir-path=/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/locales --log-file=logs\chromely.cef_20200321.log --log-severity=info --resources-dir-path=/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/ --lang=en-US --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors

DevTools listening on ws://127.0.0.1:20480/devtools/browser/d40e206c-2b73-46f4-9215-68d981416982
2020-03-21 11:27:47.423 [INFO] Running MacOSX chromium 77.0.3865.120
On CefGlue child process launch arguments:
/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/crossplatdemo --type=utility --field-trial-handle=1718379636,5549198414550298470,15611372194352481318,131072 --disable-features=OutOfBlinkCors --lang=en-US --service-sandbox-type=network --no-sandbox --locales-dir-path=/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/locales --log-file=logs\chromely.cef_20200321.log --log-severity=info --resources-dir-path=/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/ --lang=en-US --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
On CefGlue child process launch arguments:
/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/crossplatdemo --type=renderer --no-sandbox --log-file=logs\chromely.cef_20200321.log --field-trial-handle=1718379636,5549198414550298470,15611372194352481318,131072 --disable-features=OutOfBlinkCors --lang=en-US --locales-dir-path=/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/locales --log-file=logs\chromely.cef_20200321.log --log-severity=info --resources-dir-path=/Users/user/source/demo-projects/regular-chromely/CrossPlatDemo/bin/Debug/netcoreapp3.1/osx-x64/ --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
2020-03-21 11:27:47.645 [INFO] Running MacOSX chromium 77.0.3865.120
2020-03-21 11:27:47.660 [INFO] Running MacOSX chromium 77.0.3865.120

```

I assumed a window would pop up? I would appreciate any tips to debug what's going on.

Additional info:
OS: MacOS Mojave 10.14.6 
.net: dotnet-core 3.1

BR Merl

Edit: I just tried starting it on Linux and everything worked, `restore`, `build`, `run` -> downloads binaries, window appears.

**Comment by mattkol** [comment]
@merl111 if that was the first time you are running, I will suggest you try it again. I have seen this many times, the CEF binaries downloads sometimes creates race issue with the startup. But once you have the binaries, it is usually smooth.

If this is not the issue try run the application itself on the terminal (should be crossplatdemo). 

I also assume you are using the right chromelyconfig.json file. If in doubt, you can delete the file. It will fallback to using the C# default configured.

**Comment by merl111** [comment]
I have tried it a few times before, tried again, sadly same result. I tried running the application itself, has the same effect. The config should be the correct one, since I copied the osx cfg from the config directory, nevertheless, I removed the config, to with the fallback one, but still no change.

**Comment by mattkol** [comment]
When you say start successfully, meaning it is working now?

Possibly you share a screenshot of what pop ups?

Unless there are security issues, it will be good to know more of what is going on. From your logs CEF itself seems to be running successful. It is likely to do with Cocoa API or some OS security.
