### ISSUE TITLE
icudtl.dat not found in bundle

### ISSUE THREAD

**Issue by teocomi** [chromelyapps/demo-projects#20]
Hello, I'm getting the following error on osx 10.15.4, although the file _is_ there...

![image](https://user-images.githubusercontent.com/2679513/79980957-cb126880-849b-11ea-9746-d737afd5308f.png)

I've set the `RuntimeIdentifier` and config file as described in the docs.
Any ideas?

**Comment by jzlhll** [comment]
Do not use vs for mac.Have to run by dotnet cmd.

**Comment by teocomi** [comment]
That was it, thanks!

**Comment by mattkol** [comment]
@jzlhll please can you explain further. For others who may run into this.
Thanks.

**Comment by gismofx** [comment]
@jzlhll Can you please clarify? I did each command and still receive the errors:
```
[0114/230005.099851:ERROR:icu_util.cc(177)] icudtl.dat not found in bundle
[0114/230005.100196:ERROR:icu_util.cc(241)] Invalid file descriptor to ICU data received.
```

**Comment by mattkol** [comment]
@gismofx 

This may help - https://github.com/chromelyapps/demo-projects/issues/27.
