### ISSUE TITLE
Typescript sources in DevTools in ReactApp Demo

### ISSUE THREAD

**Issue by xplicit** [chromelyapps/demo-projects#28]
I tried to run ReactApp demo and can't find how to debug typescript code in devtools. When I open dev tools I see only minified js and there is no way to add sources for debug. 
I look at `dist` folder and found that source maps are generated but they are not accessible through dev tools. 

How to enable browsing source code in dev tools for chromely? I know this is possible for electron, so should be possible for chromely also.

What I tried:
 - add sourceRoot with absolute path to source for generated source maps
 - add `inlineSource: true` parcel setting in package.json
 - put src folder into dist folder
 
But nothing of these helps. Dev Tools still doesn't show sources.

**Comment by mattkol** [comment]
@xplicit React, DevTools are all third-party to Chromely. The use of them in demos is more like showing that they can be used with Chromely.  

> When I open dev tools I see only minified js and there is no way to add sources for debug.

If you see minified js then that has to do with your build process. So you may need to look closely at how Parcel does the build. More like a configuration issue with Parcel or Typescript.

**Comment by xplicit** [comment]
This is not parcel/typescript issue. If I open generated code in chrome from file system, I can browse sources and debug them. If I open these code with chromely, it's not possible to see any sources.

**Comment by mattkol** [comment]
> This is not parcel/typescript issue.

Great if you confirm it is not a parcel/typescript issue. Can you run the code with Chromely? If you can then you are left with DevTools. The intention of this project is not to go into tools usage, as I mentioned earlier. 

The internet will help or the tools primary site will provide info on how to use use them.

This may be helpful:
https://blittle.github.io/chrome-dev-tools/sources/maps.html
https://stackoverflow.com/questions/16500322/how-can-i-debug-modular-typescript-with-source-map

**Comment by xplicit** [comment]
Yes, I can run the code with chromely, just wonder how to debug the sample (Our chromely app which works on Windows doesn't work on Mac, so I try to find a way how it can be debugged on all OSes). Maybe this is source location issue, maybe it's related to `local://` protocol which couldn't be shown by dev.

Also I don't have an issues to debug ts if open the app from file system. All js/typescripts are present in dev tools in that case. So this is particular issue in chromely <-> devtools communication. I am going to try run the app in electron in near time and see if ts debugging is working, maybe this will help to resolve the issue.

**Comment by mattkol** [comment]
> Maybe this is source location issue, maybe it's related to local:// protocol which couldn't be shown by dev tools.

 ...may not be dev tools issue.
I think I have an idea what the issue is - the difference in file protocol and custom resource files loading.

First thing I will suggest is confirm that source maps are being read and loaded. You can create a [custom resource](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Browser/Handlers/DefaultResourceSchemeHandler.cs) file and log all files that are loaded and check that the [mimetypes](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Network/MimeMapper.cs) are correct. 

Info on creating custom resource handle - https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_resource_handlers.md
Ensure mimetype is correct here - https://github.com/chromelyapps/Chromely/blob/6cd69850f7ea5bdfc665f9e6fa78beceb874cc3f/src/Chromely/Browser/Handlers/DefaultResourceSchemeHandler.cs#L76

**Comment by xplicit** [comment]
Do you suppose that dev tools still tries to download them via "local://" protocol and can't do this due to their mimetypes? And will be able to load it with another custom protocol? Because in dev tools logs there are a lot of messages which clearly states that dev tools can't load *.map files. This is output from dev tools on demo reactapp project. 

![image](https://user-images.githubusercontent.com/1506904/99260941-9f4b3b80-284e-11eb-856a-88d81444fe43.png)

**Comment by xplicit** [comment]
I tried to run this snippet from dev tools console and it was returned text of the map file.

```
function getText(){
    // read text from URL location
    var request = new XMLHttpRequest();
    request.open('GET', 'local://dist/main.a9f99e37.js.map', true);
    request.send(null);
    request.onreadystatechange = function () {
        if (request.readyState === 4 && request.status === 200) {
            var type = request.getResponseHeader('Content-Type');
            console.log(type);
            console.log(request.responseText);
            
        }
    }
}
```
console output:

`text/plain`
...content of map file...

**Comment by mattkol** [comment]
> text/plain
...content of map file...

So it is loading it but with plain text.

But note that here, here you are specifically requesting the file. It will be nice to use a custom handler to make sure it is loaded properly and not affected by any dependencies.  Just to be sure.

On mimetype ...
That is correct with what we have  the -[mimetypes](https://github.com/chromelyapps/Chromely/blob/6cd69850f7ea5bdfc665f9e6fa78beceb874cc3f/src/Chromely.Core/Network/MimeMapper.cs#L954)  .map is mapped to text/plain.
````
 {
".map",
"text/plain"
},
````

> Do you suppose that dev tools still tries to download them via "local://" protocol and can't do this due to their mimetypes? 

I do not know this. I have near zero experience with source maps. Next is to find out whether a change in mimetype will help.
