### ISSUE TITLE
Can't run CefGlue.Gtk.Win.Demo

### ISSUE THREAD

**Issue by Simon-Thompson** [chromelyapps/demo-projects#3]
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
The program '[13600] cefglue_gtk_win_demo.exe' has exited with code 0 (0x0).

Steps to reproduce: 
- Download demo-projects repository
- Build Chromely.CefGlue.Gtk.Win.Demo
- Run in Debug or Release

I'm fairly new to this project, but after reading the codebase, I couldn't find any additional steps I had to go through to run the code. Am I missing something?

**Comment by mattkol** [comment]
@Simon-Thompson sorry for the late response.

You are likely missing the gtk binaries - https://github.com/chromelyapps/Chromely/tree/master/binaries/gtk32bit

Please see wiki - https://github.com/chromelyapps/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Win)

Please note it is an old wiki page and a few things may have changed.

**Comment by Simon-Thompson** [comment]
@mattkol 

Thanks for the suggestion, but after adding the gtk binaries from here - https://github.com/chromelyapps/Chromely/tree/master/binaries/gtk32bit

I'm stuck with the same problem, no change. 

I looked at the Getting Started guide you linked to, and tried manually downloading the cefglue dependencies in case they weren't installed properly from the nuget download, but not luck there either.

I've uploaded the .zip of the build, in case that can help elucidate the problem. See here: https://drive.google.com/open?id=1fvBWxeFrT0JOJUUVdEH24HbepaAdHSO2

**Comment by mattkol** [comment]
@Simon-Thompson looks like something broke gtk-win recently. Please can you try previous versions.
I am in the middle of some upgrades on my workstation and cannot debug properly. Can look at this over the weekend.

Thanks.

**Comment by mattkol** [comment]
@Simon-Thompson found what the issue is.

As a work around please can you set:
 config.HostApi = ChromelyHostApi.Gtk;

Before CreateWindow in Program.cs

  config.HostApi = ChromelyHostApi.Gtk;
                using (var window = ChromelyWindow.Create(config))

Thanks.

**Comment by Simon-Thompson** [comment]
@mattkol Excellent! It worked, thank you for your help.
