### ISSUE TITLE
BlazorDemos/ServerAppDemo can leave a process behind when window closed via Window.Close()

### ISSUE THREAD

**Issue by pragmar** [chromelyapps/demo-projects#30]
Discovered while setting up a frameless application, an orphaned process can result when WindowController.Close() is called. The leftover process is the blazorTask spawned in Program.Main.

https://github.com/chromelyapps/demo-projects/blob/master/blazor/ServerAppDemo/Program.cs

I'm able to avoid the issue by setting up a couple static fields on Program (Task/CancellationTokenSource)

```
private static Task BlazorTask;
private static CancellationTokenSource BlazorTaskTokenSource;
```

creating the task with the CancellationTokenSource token

```
// start the kestrel server in a background thread
BlazorTaskTokenSource = new CancellationTokenSource();
BlazorTask = new Task(() =>
{
    CreateHostBuilder(args, port).Build().Run();
}, BlazorTaskTokenSource.Token, TaskCreationOptions.LongRunning);
BlazorTask.Start();
```

and adding an event handler for ProcessExit

`AppDomain.CurrentDomain.ProcessExit += ProcessExit;`

```
private static void ProcessExit(object sender, EventArgs e)
{
    Task.Run(() =>
    {
        WaitHandle.WaitAny(new[] { BlazorTaskTokenSource.Token.WaitHandle });
        BlazorTask?.Dispose();
    });
    BlazorTaskTokenSource.Cancel();
}
```

I'm not 100% certain this is the right solution, however. If the above is something better done with a pull request, I'm happy submit one--just let me know.

**Comment by mattkol** [comment]
@pragmar looks like a useful feature to me. Issues like these are expected with multiple processes - Chromely, Asp.Net Core + blazor.
