### ISSUE TITLE
v_5.0/angular-react-vue cannot compile on linux

### ISSUE THREAD

**Issue by OskarZyg** [chromelyapps/demo-projects#46]
Executing xcopy is a bad practice and won't work on Linux or Mac.
Consider using https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task instead.

**Comment by mattkol** [comment]
@OskarZyg the samples using xcopy are meant for Windows Only.

There is a note in ReadMe pointing that out - https://github.com/chromelyapps/demo-projects#readme

> Notes
>
> Only the CrossPlatDemo is ready out-of-the-box for all platforms.
>
>All other demos are Windows-ready by default. You can run them, but may require a bit of knowledge on how those frameworks  work.
>
>For Angular/React/Vue using start url - local://dist/index.html it uses **xcopy** (on Windows to copy the dist folder to bin/exe folder) since it may be different for other platforms, you may have to copy the dist folder manually or replace **xcopy** functionality.
>
>For Blazor demos,** xcopy** is also used in PostBuildEvent. This may require replacement too (or manual copy) for Linux and MacOS.
