### ISSUE TITLE
The demo Chromely.CefGlue.Gtk.Linux.Demo not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by anaselhajjaji** [chromelyapps/demo-projects#6]
I'm using the dotnet sdk on Ubuntu 18.04, the build is OK but when I do dotnet run to start the app I get the following error: 
2019-09-12 14:20:35.892 [INFO] Running Linux chromium 70.0.3538.102
[0912/142035.970031:ERROR:icu_util.cc(172)] Invalid file descriptor to ICU data received.

Thank you.

**Comment by mattkol** [comment]
@anaselhajjaji  sorry for the late response.

Build and running on Linux requires publishing first. 

Please see how it is addressed here - https://github.com/chromelyapps/Chromely/issues/80
There are some other issues that address this.

Thanks.

**Comment by anaselhajjaji** [comment]
Thank you very much, it worked for me.
